/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sina_smallletters_ndkhelloword_JNIUtil */

#ifndef _Included_com_sina_smallletters_ndkhelloword_JNIUtil
#define _Included_com_sina_smallletters_ndkhelloword_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sina_smallletters_ndkhelloword_JNIUtil
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sina_smallletters_ndkhelloword_JNIUtil_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
